application: myprivatebookmarks 
version: 1
runtime: python
api_version: 1


handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: /admin/.*
  script: main.py
  login: admin

- url: /.*
  script: main.py


builtins:
- datastore_admin: on
- appstats: on

